#ifndef REQUEST_METHOD_H
#define REQUEST_METHOD_H

enum RequestMethod
{
    REQUEST_METHOD_GET,
    REQUEST_METHOD_HEAD,
    REQUEST_METHOD_POST,
    REQUEST_METHOD_PUT,
    REQUEST_METHOD_PATCH,
    REQUEST_METHOD_DELETE,
};

#endif
